/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000000",
        "on-secondary-fixed-variant": "#005137",
        "on-secondary-container": "#00714e",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#ffdcc3",
        "on-background": "#0d1c2f",
        "inverse-primary": "#bec6e0",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#d5e3fd",
        "on-surface-variant": "#45464d",
        "tertiary-container": "#2f1500",
        "tertiary-fixed-dim": "#ffb77d",
        "on-primary-fixed": "#131b2e",
        "secondary-container": "#82f5c1",
        "surface-bright": "#f8f9ff",
        "on-tertiary": "#ffffff",
        "surface-variant": "#d5e3fd",
        "outline": "#76777d",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "inverse-surface": "#233144",
        "background": "#f8f9ff",
        "on-error": "#ffffff",
        "surface-tint": "#565e74",
        "inverse-on-surface": "#ebf1ff",
        "outline-variant": "#c6c6cd",
        "surface-container-high": "#dde9ff",
        "on-primary-container": "#7c839b",
        "on-tertiary-fixed": "#2f1500",
        "primary-fixed-dim": "#bec6e0",
        "secondary-fixed-dim": "#68dba9",
        "tertiary": "#000000",
        "surface": "#f8f9ff",
        "primary-fixed": "#dae2fd",
        "secondary": "#006c4a",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#c76c00",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-secondary-fixed": "#002114",
        "on-surface": "#0d1c2f",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#85f8c4",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#ccdbf4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "1.5rem",
        "space-xs": "0.375rem",
        "space-xl": "3.5rem",
        "space-lg": "2rem",
        "margin": "3rem",
        "space-sm": "0.75rem",
        "space-md": "1.25rem",
        "margin-sm": "1.25rem",
        "gutter-sm": "1rem"
      },
      fontFamily: {
        "headline-lg": ["Newsreader", "serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Newsreader", "serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Newsreader", "serif"],
        "title-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "title-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.01em", fontWeight: "600" }],
        "title-md": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "30px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
